name: example-environment
channels:
  - conda-forge
  - bioconda
  - defaults 
dependencies:
  - python=3.9
  - r-base=4.0
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - pip
    - pip: 
- plotly
- scikit-learn
- pandas
- matplotlib
- numpy
